name: sic_home
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  mqtt_client: ^10.5.1
  retrofit: ^4.4.1
  signalr_netcore: ^1.3.9
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/bgs/
    - lib/assets/config.json

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf
